# Ignored by GitHub:
# - source: <your pages repo>
# - destination: <the build dir>
# - lsi: false
# - pygments: true

# Build settings
markdown: kramdown
exclude: []

# Custom data, available through {{ site.<variable> }}
url: "http://www.burgestrand.se/"
title: "Kim Burge Strand"
tag_text: "Kim Burge Strand"
description: "This is the description"

# Don not include categories in post permalinks
permalink: /articles/:title.html
