# Jekyll 3.0
markdown: kramdown
highlighter: rouge
permalink: /articles/:title/
kramdown:
  input: GFM
  hard_wrap: false

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Miscellaneous
author: Kim Burge Strand
description: A developer that occasionally creates things that are not code, and puts some of them here.

title: Kim Burge Strand's website
# description: ""
url: http://burgestrand.se
social:
  links:
    - https://github.com/Burgestrand
    - https://facebook.com/burgestrand
    - https://instagram.com/burgestrand
    - https://twitter.com/burgestrand
    - https://play.spotify.com/user/burgestrand

social:
  facebook: burgestrand
  twitter: burgestrand
  # google: burgestrand
  instagram: burgestrand
  # pinterest: burgestrand
  # linkedin: burgestrand
  # youtube: burgestrand
  spotify: burgestrand
  github: burgestrand
  # medium: burgestrand
  email: kim@burgestrand.se
  rubygems: burgestrand

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

paginate: 5
paginate_path: articles/:num/
related: true

plugins:
  - jemoji
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sass-converter

jekyll-mentions:
    base_url: https://github.com

exclude: [README.md, Gemfile, Gemfile.lock, CNAME, bin/]
