# Jekyll 3.0
markdown: kramdown
highlighter: rouge
permalink: /articles/:title/
kramdown:
  input: GFM
  hard_wrap: false

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Miscellaneous
author: Kim Burgestrand
description: |-
  Heartfelt software development. Sometimes other things.
title: Kim Burgestrand's website
url: https://www.burgestrand.se

social:
  - icon: mail
    url: mailto:kim@burgestrand.se
    title: kim@burgestrand.se
  - icon: github
    url: https://github.com/burgestrand
    title: "@burgestrand"
  - icon: rubygems
    url: https://rubygems.org/profiles/Burgestrand
    title: burgestrand
  - icon: mastodon
    url: https://ruby.social/@burgestrand
    title: "@burgestrand@ruby.social"

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

paginate: 5
paginate_path: articles/page-:num/
related: true

plugins:
  - jemoji
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sass-converter

exclude: [README.md, Gemfile, Gemfile.lock, CNAME, bin/]
